version: 0.0
os: linux
files:
  - source: './out'
    destination: /home/ec2-user/fe-app
    overwrite: yes

permissions:
  - object: /home/ec2-user/fe-app
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 120
      runas: ec2-user
